spring:
  datasource:
      url: "jdbc:oracle:thin:@127.0.0.1:1521/ORCL"
      username: "BPM_PX"
      password: "88960687"
      driver-class-name: "oracle.jdbc.driver.OracleDriver"
  jpa:
    show-sql: "true"
    hibernate:
      ddl-auto: "update"

server:
  port: 8080

example:
  name: mr.ma
  age: 27
